
import httpx
import asyncio
from datetime import datetime

BASE_URL = "http://localhost:8000/api/v1/procurement"

async def verify():
    async with httpx.AsyncClient() as client:
        # 1. Create Supplier
        print("Creating Supplier...")
        sup_res = await client.post(
            f"{BASE_URL}/suppliers",
            json={"name": "Verification Supplier"}
        )
        if sup_res.status_code not in (200, 201):
            with open("last_error.txt", "w", encoding="utf-8") as f:
                f.write(sup_res.text)
            print(f"Failed to create supplier: {sup_res.status_code}")
            return
        
        supplier = sup_res.json()
        supplier_id = supplier['id']
        print(f"Supplier Created: {supplier_id}")

        # 2. Create Order
        print("Creating Order...")
        order_payload = {
            "supplier_id": supplier_id,
            "items": [
                {
                    "item_name": "Verification Item",
                    "quantity": 10,
                    "unit_price": 50000,
                    "uom": "box"
                }
            ],
            "total_amount": 500000,
            "expected_delivery": "2026-02-20", # String date
            "status": "DRAFT",
            "note": "Auto-generated by verification script"
        }

        order_res = await client.post(
            f"{BASE_URL}/orders",
            json=order_payload
        )
        
        if order_res.status_code in (200, 201):
            print("SUCCESS: Order Created!")
            print(order_res.json())
        else:
            print(f"FAILED: {order_res.status_code}")
            with open("last_error.txt", "w", encoding="utf-8") as f:
                f.write(order_res.text)
            print("Error saved to last_error.txt")

if __name__ == "__main__":
    asyncio.run(verify())
